version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always  // if the container fails it will restart
    build: .  // this will look in the Docker file to build the image
    ports:
      - '80:3000'
    links:
      - mongo // this links the app container to the mongo container
  mongo:
    container_name: mongo
    image: mongo // this will pull it from docker hub
    ports:
      - '27017:27017'
